### ISSUE TITLE
Offset condition in while loop suggestion

### ISSUE THREAD

**Issue by cyans-science** [tyoo37/TGIF#4]
https://github.com/tyoo37/TGIF/blob/db3a3ab701c8084e217d844a067827a7350130af/TGIF/TGIF.py#L440C56-L440C68

I am not super sure about the logic, but should the first two conditions be grouped together in the same parentheses?
For example like this:
```python
while ((np.abs(offset_major) > adjust_th or np.abs(offset_minor) > adjust_th) and niter < maxnumiter):
```
So that the first two offset conditions are checked together before checking `maxnumiter`.

Just curious.

**Comment by tyoo37** [comment]
I know what you mean. hmm maybe the line as it is will work anyway but for clarity, it's better to put parentheses as you suggested. Thank you!
